
services:
  server:
    restart: unless-stopped
    build:
      context: scw-project
      dockerfile: Dockerfile
    entrypoint: /app/server-entrypoint.sh
    volumes:
      - static_volume:/app/backend/django_static
    expose:
      - 8000
    env_file:
      - .env
  redis:
    container_name: redis
    expose:
      - 6379
    env_file:
      - ".env"
    image: "redis"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - "redis:/data"

  worker:
    restart: unless-stopped
    build:
        context: scw-project
        dockerfile: Dockerfile
    entrypoint: /app/worker-entrypoint.sh
    env_file:
      - .env
    depends_on:
        - server
        - redis

  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432


volumes:
  postgres_data: {}
  static_volume: {}
  redis: {}